import express, { Request, Response } from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

// Set up server-side middleware
app.use(express.json({ limit: "25mb" }));

// Mock in-memory database for users and reports (to support live simulation)
const users: any[] = [
  { id: "teacher-1", username: "teacher", email: "teacher@academy.edu", password: "password", role: "teacher" },
  { id: "student-1", username: "student", email: "student@academy.edu", password: "password", role: "student" }
];

const mockReports: any[] = [];

// Helper to initialize Gemini
const getGeminiClient = () => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("WARNING: GEMINI_API_KEY is not defined in the environment. Falling back to rule-based simulation.");
    return null;
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
};

// API routes go here FIRST

// Health status check
app.get("/api/health", (req: Request, res: Response) => {
  res.json({
    status: "ok",
    timestamp: new Date().toISOString(),
    geminiConfigured: !!process.env.GEMINI_API_KEY
  });
});

// Authentication Routes
app.post("/api/auth/register", (req: Request, res: Response) => {
  const { username, email, password, role } = req.body;
  if (!username || !email || !password || !role) {
    res.status(400).json({ error: "All fields are required" });
    return;
  }
  
  const exists = users.find(u => u.email === email || u.username === username);
  if (exists) {
    res.status(400).json({ error: "User already exists" });
    return;
  }

  const newUser = {
    id: `user-${Date.now()}`,
    username,
    email,
    password, // simulation
    role: role === "teacher" ? "teacher" : "student"
  };
  users.push(newUser);

  res.json({
    message: "Registration successful",
    token: `simulated-jwt-${newUser.id}`,
    user: { id: newUser.id, username: newUser.username, email: newUser.email, role: newUser.role }
  });
});

app.post("/api/auth/login", (req: Request, res: Response) => {
  const { email, password } = req.body;
  const user = users.find(u => u.email === email && u.password === password);
  if (!user) {
    res.status(401).json({ error: "Invalid credentials" });
    return;
  }

  res.json({
    message: "Login successful",
    token: `simulated-jwt-${user.id}`,
    user: { id: user.id, username: user.username, email: user.email, role: user.role }
  });
});

app.get("/api/auth/me", (req: Request, res: Response) => {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith("Bearer simulated-jwt-")) {
    res.status(401).json({ error: "Unauthorized" });
    return;
  }

  const userId = authHeader.replace("Bearer simulated-jwt-", "");
  const user = users.find(u => u.id === userId);
  if (!user) {
    res.status(401).json({ error: "User not found" });
    return;
  }

  res.json({
    user: { id: user.id, username: user.username, email: user.email, role: user.role }
  });
});

// Active AI Analyzer Endpoint
app.post("/api/analyze", async (req: Request, res: Response) => {
  try {
    const { title, studentName, classId, files } = req.body;

    if (!files || !Array.isArray(files) || files.length === 0) {
      res.status(400).json({ error: "Please provide files to inspect." });
      return;
    }

    const reportId = `rep-${Date.now()}`;
    const mainFile = files[0];
    const totalSize = files.reduce((acc, cur) => acc + (cur.size || 0), 0);
    
    // Concat files for analysis content
    let mergedContent = "";
    for (const f of files) {
      mergedContent += `\nFILEPATH: ${f.name}\nCONTENT:\n${f.content}\n-----------------------------------\n`;
    }

    // Limit to prevent token overflow
    if (mergedContent.length > 300000) {
      mergedContent = mergedContent.substring(0, 300000) + "\n... [TRUNCATED DUE TO SIZE LIMITS] ...";
    }

    const ai = getGeminiClient();

    if (!ai) {
      // Return beautiful simulated detector report if Gemini SDK token is absent
      console.log("Gemini API key is not set. Generating deterministic smart analysis response.");
      
      const containsAiIndicators = 
        mergedContent.includes("As an AI language model") ||
        mergedContent.includes("Sure, here is") ||
        mergedContent.includes("let me know if you need more help") ||
        mergedContent.includes("// ChatGPT") ||
        mergedContent.includes("// generated by ai") ||
        mergedContent.includes("Lorem ipsum") ||
        mergedContent.includes("className=\"flex flex-col items-center justify-center min-h-screen"); // typical clean structure
      
      const score = containsAiIndicators ? 92 : (mergedContent.length % 40) + 12; // pseudo-calculated score
      const confidence = score > 80 ? "High" : score > 40 ? "Medium" : "Low";
      const language = mainFile.name.endsWith(".js") ? "JavaScript" :
                       mainFile.name.endsWith(".ts") ? "TypeScript" :
                       mainFile.name.endsWith(".tsx") ? "React (TSX)" :
                       mainFile.name.endsWith(".py") ? "Python" :
                       mainFile.name.endsWith(".java") ? "Java" :
                       mainFile.name.endsWith(".css") ? "CSS" : "Plain Text";

      const simulatedReport = {
        id: reportId,
        title: title || "AI Scanning Analysis",
        studentName: studentName || "Anonymous Student",
        studentId: "stu-" + Math.floor(1000 + Math.random() * 9000),
        classId: classId || "General Sandbox",
        fileName: mainFile.name,
        fileSize: totalSize,
        timestamp: new Date().toISOString(),
        aiScore: score,
        humanScore: 100 - score,
        confidenceLevel: confidence,
        language,
        overallExplanation: `### Scanner Analysis Report
We scanned ${files.length} file(s) and detected a **${score}% AI probability score**.

Development Environment Notice: **GEMINI_API_KEY** was not found in active secrets. To experience full, intelligent, custom explanations generated live by Gemini, set up your \`GEMINI_API_KEY\` in **Settings > Secrets** in AI Studio!

#### Observed Patterns:
- **Cleanliness:** Code displays zero typos and standard mechanical patterns.
- **Complexity:** Perfectly structured without experimental iterations.
- **Language Detection:** Identified as ${language}.`,
        metrics: {
          repeatedPatterns: score > 70 ? 88 : 15,
          commentPatterns: score > 60 ? 94 : 20,
          namingConventions: score > 50 ? 90 : 25,
          styleConsistency: score > 40 ? 98 : 30,
          complexityScore: score > 30 ? 85 : 35
        },
        suspiciousLines: [
          {
            lineNumber: 2,
            snippet: "const mainResult = () => {",
            score: score > 50 ? 80 : 20,
            reason: "Canonical structure commonly used by ChatGPT models in standard layouts."
          }
        ],
        comparisons: [
          {
            feature: "Variable Naming",
            observedPattern: "Extremely tidy standard variable formats (e.g. userProfileData, fetchPayload)",
            aiTypicalPattern: "Strict camelCase dictionary names, rarely incorporating idiosyncratic shorthand",
            verdict: score > 50 ? "Typical AI" as const : "Likely Human" as const
          }
        ],
        recommendations: [
          "Set up your official Google Gemini API Key in the settings for real analyses.",
          "Check the file history or prompt the student with direct questions on their choice of algorithms.",
          "Request a quick screenshare of their local workspace git log history."
        ]
      };
      
      mockReports.push(simulatedReport);
      res.json(simulatedReport);
      return;
    }

    // Call real Gemini model in structured JSON mode
    const systemInstruction = `You are a professional academic integrity inspector, an AI Homework Detector expert.
Analyze the provided code or text submission. Your job is to check for markers of AI generation (like ChatGPT, Claude, Copilot, or Gemini).
Markers of AI include:
- Over-clean structure with absolutely perfect alignment and no conversational typos or trailing debug comments.
- Highly verbose, textbook-quality descriptions or boilerplate comments (e.g., '// This function handles the request' for obvious code).
- Standard variables like 'temp', 'result', 'data' inside perfectly crafted modular components.
- ChatGPT style polite prefixes/suffixes in text or code files (e.g., "Certainly! Here is...", "// I hope this helps!").
- Repeated algorithmic styles and lack of experimental or non-standard variations inside files.

Evaluate the content forensically. Provide a percentage score (0-100) where 100 means definitely AI generated and 0 means purely human written. Provide the structure as JSON. Make the overall explanation beautifully formatted in Markdown.`;

    const prompt = `Please inspect this student submission.
Title: "${title || "Not Specified"}"
Student: "${studentName || "Anonymous"}"
Class: "${classId || "Sandbox"}"

FILES TO INSPECT:
${mergedContent}`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            aiScore: { type: Type.INTEGER, description: "AI probability percentage score (0-100)." },
            confidenceLevel: { type: Type.STRING, description: "Scanner confidence: 'High', 'Medium', or 'Low'." },
            language: { type: Type.STRING, description: "Predominant language detected (e.g. JavaScript, Python, CSS, Plain Text)." },
            overallExplanation: { type: Type.STRING, description: "Thorough architectural explanation in beautiful Markdown explaining why or why not this feels AI-generated." },
            metrics: {
              type: Type.OBJECT,
              properties: {
                repeatedPatterns: { type: Type.INTEGER, description: "Score 0-100" },
                commentPatterns: { type: Type.INTEGER, description: "Score 0-100" },
                namingConventions: { type: Type.INTEGER, description: "Score 0-100" },
                styleConsistency: { type: Type.INTEGER, description: "Score 0-100" },
                complexityScore: { type: Type.INTEGER, description: "Score 0-100" }
              },
              required: ["repeatedPatterns", "commentPatterns", "namingConventions", "styleConsistency", "complexityScore"]
            },
            suspiciousLines: {
              type: Type.ARRAY,
              description: "Highlight lines that look suspiciously generated.",
              items: {
                type: Type.OBJECT,
                properties: {
                  lineNumber: { type: Type.INTEGER, description: "Line number approx in files where violation exists." },
                  snippet: { type: Type.STRING, description: "The specific line snippet or code segment." },
                  score: { type: Type.INTEGER, description: "Probability 0-100 this block is generated by AI." },
                  reason: { type: Type.STRING, description: "Specifically, why is this code snippet suspicious?" }
                },
                required: ["lineNumber", "snippet", "score", "reason"]
              }
            },
            comparisons: {
              type: Type.ARRAY,
              description: "Comparison metrics",
              items: {
                type: Type.OBJECT,
                properties: {
                  feature: { type: Type.STRING, description: "Pattern checked e.g. Comments, Typos, Algorithmic Choice." },
                  observedPattern: { type: Type.STRING, description: "Observed in project." },
                  aiTypicalPattern: { type: Type.STRING, description: "Typical AI generator style." },
                  verdict: { type: Type.STRING, description: "Verdict: Must be 'Typical AI', 'Suspicious', or 'Likely Human'." }
                },
                required: ["feature", "observedPattern", "aiTypicalPattern", "verdict"]
              }
            },
            recommendations: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Actionable validation steps/recommendations for the instructor."
            }
          },
          required: ["aiScore", "confidenceLevel", "language", "overallExplanation", "metrics", "suspiciousLines", "comparisons", "recommendations"]
        }
      }
    });

    const outputText = response.text;
    if (!outputText) {
      throw new Error("Empty response received from Gemini.");
    }

    const reportData = JSON.parse(outputText.trim());
    
    // Add transaction stats
    const processedReport = {
      id: reportId,
      title: title || "AI Scan Submission",
      studentName: studentName || "Anonymous Student",
      studentId: "stu-" + Math.floor(1000 + Math.random() * 9000),
      classId: classId || "Sandbox",
      fileName: mainFile.name,
      fileSize: totalSize,
      timestamp: new Date().toISOString(),
      ...reportData,
      humanScore: 100 - reportData.aiScore,
    };

    mockReports.push(processedReport);
    res.json(processedReport);

  } catch (error: any) {
    console.error("AI Analysis Error:", error);
    res.status(500).json({ error: "Failed to scan homework: " + error.message });
  }
});

// Configure Vite middleware / asset serving
const startServer = async () => {
  if (process.env.NODE_ENV !== "production") {
    // Development Mode
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    
    app.use(vite.middlewares);
    console.log("Mounted Vite development middleware.");
  } else {
    // Production Mode
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    
    app.get("*", (req: Request, res: Response) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
    console.log(`Serving static production build from: ${distPath}`);
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`AI Homework Detector listening on port http://localhost:${PORT}`);
  });
};

startServer().catch(err => {
  console.error("Failed to boot server:", err);
});
