export const translations = {
  en: {
    title: "AI Homework Detector",
    tagline: "Futuristic Academic Integrity & AI Detection",
    description: "Scan files, code projects, or ZIP folders using pattern analysis to detect AI-generated work, explore suspicious lines, and generate forensic compliance reports.",
    getStarted: "Launch Scanner",
    teacherPortal: "Educator Console",
    studentPortal: "Student Terminal",
    history: "Detection Log",
    uploadTitle: "Drop Submission Terminal",
    uploadPlaceholder: "Drag & Drop files or a ZIP archive, or click to browse",
    supportedFormats: "Supported: ZIP, PY, JS, TS, HTML, CSS, PY, JAVA, TXT, PDF, DOCX",
    checkingFiles: "Extracting elements & inspecting trees...",
    buttonScan: "Initiate Scanner Analysis",
    scanning: "Analyzing linguistic markers & structural patterns...",
    resultsTitle: "Forensic Spectrum Result",
    aiProbability: "AI Probability Score",
    humanPercentage: "Human Integrity Index",
    confidence: "Detection Confidence",
    explanation: "AI Pattern Diagnostics",
    suspiciousLines: "Highlighted Code Violations",
    comparisons: "Behavioral Style Contrast",
    recommendations: "Instructional Actions",
    closeScanner: "Close Compliance Report",
    dashboardHeader: "Educator Command Station",
    studentHeader: "Student Analysis Ledger",
    scansHistory: "Submission Queue",
    statsAvgScore: "Average AI Score",
    statsTotalScans: "Files Audited",
    statsFlagged: "Integrity Flags",
    statsWarning: "Integrity Warnings",
    filterStudent: "Search student...",
    filterClass: "All Classes",
    thresholdSetting: "Flag Notification Limits",
    flagThreshold: "Severe Flag Threshold",
    warningThreshold: "Warning Threshold",
    saveSettings: "Calibrate Trigger Metrics",
    languageToggle: "Tilni o'zgartirish",
    currentLanguageName: "English",
    loginRegister: "Authenticate Node",
    signOut: "De-authenticate",
    username: "Operator Codex",
    email: "Academic Email",
    password: "Security Decryption Key",
    roleTeacher: "Educator / Faculty",
    roleStudent: "Submitter / Student",
    formSubmit: "Commit Connection",
    notConnectedNote: "Note: Real Gemini intelligence mode can be unlocked inside Settings > Secrets."
  },
  uz: {
    title: "AI Uy Vazifasi Detektori",
    tagline: "Akademik Halollik va AI Tahlil Tizimi",
    description: "Talabalar yuborgan kod, loyiha va ZIP fayllarini skaner qiling. AI tomonidan yozilganini aniqlang, shubhali qatorlarni ko'ring va tahlil hisobotini oling.",
    getStarted: "Skanerni Boshlash",
    teacherPortal: "O'qituvchi Konsoli",
    studentPortal: "Talaba Terminali",
    history: "Skanerlash Tarixi",
    uploadTitle: "Yuborish Fayllari Terminali",
    uploadPlaceholder: "Fayllarni yoki ZIP arxivni bu yerga torting, yoki bosing",
    supportedFormats: "Formatlar: ZIP, PDF, DOCX, TXT, JS, TS, HTML, CSS, PY, JAVA",
    checkingFiles: "Fayllar tekshirilmoqda va daraxt tuzilmoqda...",
    buttonScan: "Tahlilni Faollashtirish",
    scanning: "Hujjatlar tahlili va lingvistik markerlar qidirilmoqda...",
    resultsTitle: "Forensik Tahlil Natijalari",
    aiProbability: "AI Ehtimollik Darajasi",
    humanPercentage: "Inson Halolligi Indeksi",
    confidence: "Ishonch Darajasi",
    explanation: "AI Shpargalka Tashhisi",
    suspiciousLines: "Shubhali Belgilangan Qatorlar",
    comparisons: "Uslub va Xulq-Atvor Kontrasti",
    recommendations: "O'qituvchi Taviyalari",
    closeScanner: "Hisobotni Yopish",
    dashboardHeader: "O'qituvchi Qo'mondonlik Tizimi",
    studentHeader: "Talaba Ko'rsatkichlari",
    scansHistory: "Navbatdagi Vazifalar",
    statsAvgScore: "O'rtacha AI balli",
    statsTotalScans: "Tekshirilgan Fayllar",
    statsFlagged: "Og'ir Shubhali",
    statsWarning: "Ogohlantirishlar",
    filterStudent: "Talabani qidirish...",
    filterClass: "Barcha sinflar",
    thresholdSetting: "Signal Chegara Boshqaruvi",
    flagThreshold: "Og'ir Chegara Parametri",
    warningThreshold: "Ogohlantirish Parametri",
    saveSettings: "Metrikalarni Saqlash",
    languageToggle: "Switch to English",
    currentLanguageName: "O'zbekcha",
    loginRegister: "Xavfsizlik Tizimiga Kirish",
    signOut: "Tizimdan Chiqish",
    username: "Login/Ism",
    email: "Akademik Email",
    password: "Maxfiy Parol",
    roleTeacher: "O'qituvchi / Fakultet",
    roleStudent: "Talaba / Surbmitter",
    formSubmit: "Kirishni Tasdiqlash",
    notConnectedNote: "Eslatma: Haqiqiy Gemini AI tahlilini faollashtirish uchun Settings > Secrets qismida API kalitini sozlang."
  }
};

export type Language = 'en' | 'uz';
